require('dotenv').config();
const path = require('path');
const crypto = require('crypto');
const express = require('express');
const session = require('express-session');
const pgSession = require('connect-pg-simple')(session);
const { Pool } = require('pg');
const bcrypt = require('bcryptjs');
const multer = require('multer');
const { v2: cloudinary } = require('cloudinary');

const app = express();
const PORT = Number(process.env.PORT || 3000);
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.DATABASE_URL?.includes('localhost') ? false : { rejectUnauthorized: false } });
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 100 * 1024 * 1024 } });
app.set('trust proxy', 1);
app.use(express.json({ limit: '2mb' }));
app.use(session({ store: new pgSession({ pool, tableName: 'user_sessions', createTableIfMissing: true }), secret: process.env.SESSION_SECRET || 'local-development-only-change-me', resave: false, saveUninitialized: true, cookie: { httpOnly: true, sameSite: 'lax', secure: process.env.NODE_ENV === 'production', maxAge: 1000 * 60 * 60 * 24 * 365 } }));

const q = (text, values = []) => pool.query(text, values);
const now = () => new Date().toISOString();
function visitorId(req) { if (!req.session.visitorId) req.session.visitorId = crypto.randomUUID(); return req.session.visitorId; }
function clientIp(req) { return String(req.ip || req.socket.remoteAddress || '').replace('::ffff:', '').slice(0, 64); }
async function row(sql, vals) { return (await q(sql, vals)).rows[0]; }
async function logSecurity(req, route, kind = 'restricted_route') { await q('INSERT INTO security_events (ip_address, visitor_id, route, kind, user_agent, created_at) VALUES ($1,$2,$3,$4,$5,NOW())', [clientIp(req), visitorId(req), route, kind, String(req.get('user-agent') || '').slice(0, 400)]); }
async function blocked(req) { return row('SELECT scope FROM blocked_visitors WHERE active = TRUE AND (ip_address=$1 OR visitor_id=$2) ORDER BY created_at DESC LIMIT 1', [clientIp(req), visitorId(req)]); }
async function requireAdmin(req, res, next) { if (req.session.isAdmin) return next(); res.status(401).json({ error: 'Yetkili oturumu gerekli.' }); }

async function init() {
  await q(`CREATE EXTENSION IF NOT EXISTS pgcrypto;
    CREATE TABLE IF NOT EXISTS site_settings (key TEXT PRIMARY KEY, value JSONB NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS admins (id SERIAL PRIMARY KEY, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS security_events (id BIGSERIAL PRIMARY KEY, ip_address TEXT NOT NULL, visitor_id UUID, route TEXT NOT NULL, kind TEXT NOT NULL, user_agent TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS blocked_visitors (id BIGSERIAL PRIMARY KEY, ip_address TEXT, visitor_id UUID, scope TEXT NOT NULL CHECK(scope IN ('site','archive')), active BOOLEAN NOT NULL DEFAULT TRUE, note TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS archive_creators (id BIGSERIAL PRIMARY KEY, visitor_id UUID UNIQUE NOT NULL, ip_address TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_archive_at TIMESTAMPTZ, archive_reads INTEGER NOT NULL DEFAULT 0);
    CREATE TABLE IF NOT EXISTS archives (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), title TEXT NOT NULL, description TEXT DEFAULT '', owner_visitor_id UUID, visibility TEXT NOT NULL DEFAULT 'private' CHECK(visibility IN ('public','private','admin','password')), status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','hidden')), password_hash TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS archive_items (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), archive_id UUID NOT NULL REFERENCES archives(id) ON DELETE CASCADE, parent_id UUID REFERENCES archive_items(id) ON DELETE CASCADE, kind TEXT NOT NULL CHECK(kind IN ('folder','text','link','image','video')), title TEXT NOT NULL, body TEXT, media_url TEXT, cloudinary_id TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS announcements (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), type TEXT NOT NULL CHECK(type IN ('toast','modal','article')), title TEXT NOT NULL, body TEXT NOT NULL, author TEXT, color TEXT DEFAULT '#b89657', image_url TEXT, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS team_members (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, role TEXT, bio TEXT, image_url TEXT, visible BOOLEAN NOT NULL DEFAULT TRUE, sort_order INTEGER NOT NULL DEFAULT 0);
  `);
  const existing = await row('SELECT id FROM admins WHERE username=$1', ['yonetici']);
  if (!existing) await q('INSERT INTO admins(username,password_hash) VALUES($1,$2)', ['yonetici', await bcrypt.hash(process.env.ADMIN_PASSWORD || '123123', 12)]);
  const defaults = {
    brand: { name: 'Vecd ile Müdafaa Birliği', eyebrow: 'VMB / 01', heroTitle: 'Hafıza, irade ve müşterek bir istikamet.', heroText: 'Vecd ile Müdafaa Birliği; düşünceyi, belleği ve üretimi ortak bir zeminde buluşturan bağımsız bir topluluktur.', quote: 'Birlik, aynı sesi yükseltmek değil; aynı sorumluluğu taşımaktır.' },
    about: { title: 'Hakkımızda', body: 'VMB; fikir, emek ve arşiv kültürü etrafında buluşan insanların açık çalışma alanıdır.' },
    contact: { title: 'İletişim', links: [{ label: 'Instagram', icon: 'instagram', url: '', active: false }, { label: 'Discord', icon: 'discord', url: '', active: false }, { label: 'E-posta', icon: 'mail', url: '', active: true }, { label: 'Web', icon: 'globe', url: '', active: false }, { label: 'Reddit', icon: 'reddit', url: '', active: false }, { label: 'WhatsApp', icon: 'whatsapp', url: '', active: false }, { label: 'X', icon: 'x', url: '', active: false }] }
  };
  for (const [key, value] of Object.entries(defaults)) await q('INSERT INTO site_settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO NOTHING', [key, value]);
}

app.use(async (req, res, next) => {
  try { const ban = await blocked(req); if (ban?.scope === 'site' && !req.path.startsWith('/api/admin')) return res.status(403).sendFile(path.join(__dirname, 'public', 'blocked.html')); next(); } catch (e) { next(e); }
});
app.get(['/admin','/yonetim','/yonet'], async (req, res, next) => { try { await logSecurity(req, req.path); res.status(403).sendFile(path.join(__dirname, 'public', 'restricted.html')); } catch (e) { next(e); } });

app.get('/api/site', async (req, res, next) => { try { const settings = (await q('SELECT key,value FROM site_settings')).rows.reduce((a, x) => ({ ...a, [x.key]: x.value }), {}); const announcements = (await q("SELECT * FROM announcements WHERE active=true ORDER BY created_at DESC")).rows; const team = (await q('SELECT * FROM team_members WHERE visible=true ORDER BY sort_order,name')).rows; res.json({ settings, announcements, team }); } catch (e) { next(e); } });
app.get('/api/archives', async (req, res, next) => { try { const vid = visitorId(req); const archives = (await q(`SELECT a.*, CASE WHEN a.owner_visitor_id=$1 THEN true ELSE false END AS owner FROM archives a WHERE a.visibility='public' AND a.status='approved' OR a.owner_visitor_id=$1 ORDER BY a.updated_at DESC`, [vid])).rows; res.json({ archives }); } catch (e) { next(e); } });
app.get('/api/archives/:id', async (req, res, next) => { try { const a = await row('SELECT * FROM archives WHERE id=$1', [req.params.id]); if (!a) return res.sendStatus(404); const own = a.owner_visitor_id === visitorId(req); if (!(own || (a.visibility === 'public' && a.status === 'approved') || req.session.isAdmin)) return res.sendStatus(403); if (!own) await q('UPDATE archive_creators SET archive_reads=archive_reads+1 WHERE visitor_id=$1', [a.owner_visitor_id]); const items = (await q('SELECT * FROM archive_items WHERE archive_id=$1 ORDER BY kind DESC, created_at', [a.id])).rows; res.json({ archive: a, items }); } catch (e) { next(e); } });
app.post('/api/archives', async (req, res, next) => { try { const ban = await blocked(req); if (ban?.scope === 'archive' || ban?.scope === 'site') return res.status(403).json({ error: 'Arşiv gönderme erişiminiz kapatılmıştır.' }); const title = String(req.body.title || '').trim().slice(0, 140); if (!title) return res.status(400).json({ error: 'Başlık gerekli.' }); const vid = visitorId(req); await q('INSERT INTO archive_creators(visitor_id,ip_address,last_archive_at) VALUES($1,$2,NOW()) ON CONFLICT(visitor_id) DO UPDATE SET last_archive_at=NOW(),ip_address=EXCLUDED.ip_address', [vid, clientIp(req)]); const a = await row('INSERT INTO archives(title,description,owner_visitor_id) VALUES($1,$2,$3) RETURNING *', [title, String(req.body.description || '').slice(0, 3000), vid]); res.status(201).json({ archive: a }); } catch (e) { next(e); } });
app.patch('/api/archives/:id/visibility', async (req, res, next) => { try { const a = await row('SELECT * FROM archives WHERE id=$1', [req.params.id]); if (!a || (a.owner_visitor_id !== visitorId(req) && !req.session.isAdmin)) return res.sendStatus(403); const visibility = ['public','private'].includes(req.body.visibility) ? req.body.visibility : 'private'; await q('UPDATE archives SET visibility=$1,status=CASE WHEN $1=\'public\' THEN \'pending\' ELSE \'hidden\' END,updated_at=NOW() WHERE id=$2', [visibility, a.id]); res.json({ ok: true }); } catch (e) { next(e); } });
app.post('/api/archives/:id/items', upload.single('file'), async (req,res,next) => { try { const a=await row('SELECT * FROM archives WHERE id=$1',[req.params.id]); if(!a || (a.owner_visitor_id!==visitorId(req) && !req.session.isAdmin)) return res.sendStatus(403); const kind=['folder','text','link','image','video'].includes(req.body.kind)?req.body.kind:'text'; let mediaUrl=null,cloudId=null; if(req.file){ if(!process.env.CLOUDINARY_CLOUD_NAME)return res.status(503).json({error:'Medya yüklemek için Cloudinary ortam değişkenleri gerekli.'}); cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET}); const result=await new Promise((resolve,reject)=>cloudinary.uploader.upload_stream({folder:'vmb-archives',resource_type:'auto'},(e,r)=>e?reject(e):resolve(r)).end(req.file.buffer));mediaUrl=result.secure_url;cloudId=result.public_id; } const item=await row('INSERT INTO archive_items(archive_id,parent_id,kind,title,body,media_url,cloudinary_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[a.id,req.body.parent_id||null,kind,String(req.body.title||'Yeni kayıt').slice(0,140),String(req.body.body||'').slice(0,10000),mediaUrl||req.body.media_url||null,cloudId]);res.status(201).json(item); }catch(e){next(e)} });

app.post('/api/auth/login', async (req, res, next) => { try { const admin = await row('SELECT * FROM admins WHERE username=$1', [String(req.body.username || 'yonetici')]); if (!admin || !(await bcrypt.compare(String(req.body.password || ''), admin.password_hash))) return res.status(401).json({ error: 'Bilgiler doğrulanamadı.' }); req.session.isAdmin = true; req.session.adminId = admin.id; res.json({ ok: true }); } catch (e) { next(e); } });
app.post('/api/auth/logout', (req, res) => req.session.destroy(() => res.json({ ok: true })));
app.get('/api/admin/dashboard', requireAdmin, async (req,res,next) => { try { const [archives, pending, creators, security] = await Promise.all(['SELECT count(*) FROM archives','SELECT count(*) FROM archives WHERE status=\'pending\'','SELECT count(*) FROM archive_creators','SELECT count(*) FROM security_events'].map(async x => (await q(x)).rows[0].count)); res.json({ archives, pending, creators, security }); } catch(e){next(e)} });
app.get('/api/admin/:resource', requireAdmin, async (req,res,next) => { try { const map = { archives: 'SELECT * FROM archives ORDER BY updated_at DESC', announcements: 'SELECT * FROM announcements ORDER BY created_at DESC', team: 'SELECT * FROM team_members ORDER BY sort_order,name', security: 'SELECT * FROM security_events ORDER BY created_at DESC LIMIT 200', creators: 'SELECT c.*, COUNT(a.id) AS archive_count FROM archive_creators c LEFT JOIN archives a ON a.owner_visitor_id=c.visitor_id GROUP BY c.id ORDER BY c.created_at', bans: 'SELECT * FROM blocked_visitors ORDER BY created_at DESC', settings: 'SELECT key,value,updated_at FROM site_settings ORDER BY key' }; if (!map[req.params.resource]) return res.sendStatus(404); res.json((await q(map[req.params.resource])).rows); } catch(e){next(e)} });
app.put('/api/admin/settings/:key', requireAdmin, async (req,res,next) => { try { if (!['brand','about','contact'].includes(req.params.key)) return res.sendStatus(400); await q('INSERT INTO site_settings(key,value,updated_at) VALUES($1,$2,NOW()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=NOW()', [req.params.key, req.body]); res.json({ ok:true }); } catch(e){next(e)} });
app.post('/api/admin/announcements', requireAdmin, async (req,res,next) => { try { const d=req.body; const x=await row('INSERT INTO announcements(type,title,body,author,color,image_url,active) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[d.type,d.title,d.body,d.author||'',d.color||'#b89657',d.image_url||'',d.active!==false]);res.status(201).json(x)}catch(e){next(e)} });
app.patch('/api/admin/announcements/:id', requireAdmin, async (req,res,next) => { try { const d=req.body; await q('UPDATE announcements SET title=$1,body=$2,author=$3,color=$4,image_url=$5,active=$6 WHERE id=$7',[d.title,d.body,d.author||'',d.color||'#b89657',d.image_url||'',d.active!==false,req.params.id]);res.json({ok:true})}catch(e){next(e)} });
app.delete('/api/admin/announcements/:id', requireAdmin, async (req,res,next) => { try { await q('DELETE FROM announcements WHERE id=$1',[req.params.id]);res.json({ok:true})}catch(e){next(e)} });
app.post('/api/admin/team', requireAdmin, async (req,res,next) => { try { const d=req.body;res.json(await row('INSERT INTO team_members(name,role,bio,image_url,visible,sort_order) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[d.name,d.role||'',d.bio||'',d.image_url||'',d.visible!==false,Number(d.sort_order||0)]))}catch(e){next(e)} });
app.patch('/api/admin/archives/:id', requireAdmin, async (req,res,next) => { try { const d=req.body, v=['public','private','admin','password'].includes(d.visibility)?d.visibility:'private'; const status=v==='public'?'approved':'hidden'; const hash=d.password ? await bcrypt.hash(String(d.password),12):null; await q('UPDATE archives SET visibility=$1,status=$2,password_hash=COALESCE($3,password_hash),updated_at=NOW() WHERE id=$4',[v,status,hash,req.params.id]);res.json({ok:true})}catch(e){next(e)} });
app.post('/api/admin/bans', requireAdmin, async (req,res,next) => { try { const d=req.body; if(!d.ip_address&&!d.visitor_id) return res.status(400).json({error:'IP veya ziyaretçi kimliği gerekli.'});res.json(await row('INSERT INTO blocked_visitors(ip_address,visitor_id,scope,note) VALUES($1,$2,$3,$4) RETURNING *',[d.ip_address||null,d.visitor_id||null,d.scope==='archive'?'archive':'site',d.note||'']))}catch(e){next(e)} });
app.patch('/api/admin/bans/:id', requireAdmin, async (req,res,next) => { try { await q('UPDATE blocked_visitors SET active=$1 WHERE id=$2',[req.body.active===true,req.params.id]);res.json({ok:true})}catch(e){next(e)} });
app.patch('/api/admin/password', requireAdmin, async (req,res,next) => { try { if(String(req.body.password||'').length<8)return res.status(400).json({error:'En az 8 karakter kullanın.'});await q('UPDATE admins SET password_hash=$1,updated_at=NOW() WHERE id=$2',[await bcrypt.hash(req.body.password,12),req.session.adminId]);res.json({ok:true})}catch(e){next(e)} });
app.post('/api/admin/archive-items', requireAdmin, upload.single('file'), async (req,res,next) => { try { const d=req.body; let mediaUrl=null, cloudId=null; if(req.file){ if(!process.env.CLOUDINARY_CLOUD_NAME)return res.status(503).json({error:'Cloudinary Railway ortam değişkenleri yapılandırılmamış.'}); cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET}); const result=await new Promise((resolve,reject)=>cloudinary.uploader.upload_stream({folder:'vmb-archives',resource_type:'auto'},(e,r)=>e?reject(e):resolve(r)).end(req.file.buffer)); mediaUrl=result.secure_url;cloudId=result.public_id; } const item=await row('INSERT INTO archive_items(archive_id,parent_id,kind,title,body,media_url,cloudinary_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[d.archive_id,d.parent_id||null,d.kind,d.title,String(d.body||''),mediaUrl,cloudId]);res.status(201).json(item)}catch(e){next(e)} });
app.delete('/api/admin/archive-items/:id', requireAdmin, async (req,res,next) => { try { const item=await row('SELECT * FROM archive_items WHERE id=$1',[req.params.id]); if(!item)return res.sendStatus(404); if(item.cloudinary_id && process.env.CLOUDINARY_CLOUD_NAME){ cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET}); await cloudinary.uploader.destroy(item.cloudinary_id,{resource_type:item.kind==='video'?'video':'image',invalidate:true}); } await q('DELETE FROM archive_items WHERE id=$1',[item.id]);res.json({ok:true}); }catch(e){next(e)} });
app.use(express.static(path.join(__dirname, 'public')));
app.get('*', (req,res) => res.sendFile(path.join(__dirname,'public','index.html')));
app.use((err,req,res,next)=>{ console.error(err); res.status(500).json({error:'Beklenmeyen bir hata oluştu.'}); });
init().then(()=>app.listen(PORT,()=>console.log(`VMB listening on ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
